apiVersion: apps/v1
kind: Deployment

metadata:
  name: server-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: augustbright/worlds-server
          ports:
            - containerPort: 3000
          env:
            - name: JWT_EXPIRES_IN
              value: 6000s
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server
                  key: JWT_SECRET
            
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: server
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: server
                  key: GOOGLE_CLIENT_SECRET
            - name: GOOGLE_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  name: server
                  key: GOOGLE_CALLBACK_URL

            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: server
                  key: MONGO_URL
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: server
                  key: MONGO_DB_NAME